name: Build and sign on release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-sign:
    runs-on: windows-2022
    name: Build app and sign exe
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Azure login (OIDC)
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign executable
        uses: azure/artifact-signing-action@v2
        with:
          endpoint: https://neu.codesigning.azure.net/
          signing-account-name: code-signing
          certificate-profile-name: ibirico-certificate-profile
          files-folder: ${{ github.workspace }}\target\release
          files-folder-filter: exe
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256
